USE [{DBNAME}] 
 
/****** Object:  Table [dbo].[USERS]    Script Date: 27.07.2021 07:54:45 ******/
SET ANSI_NULLS ON 
 
SET QUOTED_IDENTIFIER ON 
 
CREATE TABLE [dbo].[USERS]( 
	[GUID] [uniqueidentifier] NOT NULL,
	[CODE] [nvarchar](25) NULL,
	[NAME] [nvarchar](50) NULL,
	[PWD] [nvarchar](25) NULL,
	[ROLE] [nvarchar](25) NULL,
	[STATUS] [smallint] NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
( 
	[GUID] ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY] 
) ON [PRIMARY] 
 
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_GUID]  DEFAULT (newid()) FOR [GUID] 
 