USE [master] 
 
CREATE DATABASE [{DBNAME}] 
 CONTAINMENT = NONE 
 ON  PRIMARY 
( NAME = N'{DBNAME}', FILENAME = N'{FOLDER_NAME}\{DBNAME}.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ) 
 LOG ON 
( NAME = N'{DBNAME}_log', FILENAME = N'{FOLDER_NAME}\{DBNAME}_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB ) 
 WITH CATALOG_COLLATION = DATABASE_DEFAULT 
 
ALTER DATABASE [{DBNAME}] SET COMPATIBILITY_LEVEL = 150 
 
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled')) 
begin 
EXEC [{DBNAME}].[dbo].[sp_fulltext_database] @action = 'enable' 
end 
 
ALTER DATABASE [{DBNAME}] SET ANSI_NULL_DEFAULT OFF 
 
ALTER DATABASE [{DBNAME}] SET ANSI_NULLS OFF 
 
ALTER DATABASE [{DBNAME}] SET ANSI_PADDING OFF 
 
ALTER DATABASE [{DBNAME}] SET ANSI_WARNINGS OFF 
 
ALTER DATABASE [{DBNAME}] SET ARITHABORT OFF 
 
ALTER DATABASE [{DBNAME}] SET AUTO_CLOSE OFF 
 
ALTER DATABASE [{DBNAME}] SET AUTO_SHRINK OFF 
 
ALTER DATABASE [{DBNAME}] SET AUTO_UPDATE_STATISTICS ON 
 
ALTER DATABASE [{DBNAME}] SET CURSOR_CLOSE_ON_COMMIT OFF 
 
ALTER DATABASE [{DBNAME}] SET CURSOR_DEFAULT  GLOBAL 
 
ALTER DATABASE [{DBNAME}] SET CONCAT_NULL_YIELDS_NULL OFF 
 
ALTER DATABASE [{DBNAME}] SET NUMERIC_ROUNDABORT OFF 
 
ALTER DATABASE [{DBNAME}] SET QUOTED_IDENTIFIER OFF 
 
ALTER DATABASE [{DBNAME}] SET RECURSIVE_TRIGGERS OFF 
 
ALTER DATABASE [{DBNAME}] SET  DISABLE_BROKER 
 
ALTER DATABASE [{DBNAME}] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
 
ALTER DATABASE [{DBNAME}] SET DATE_CORRELATION_OPTIMIZATION OFF 
 
ALTER DATABASE [{DBNAME}] SET TRUSTWORTHY OFF 
 
ALTER DATABASE [{DBNAME}] SET ALLOW_SNAPSHOT_ISOLATION OFF 
 
ALTER DATABASE [{DBNAME}] SET PARAMETERIZATION SIMPLE 
 
ALTER DATABASE [{DBNAME}] SET READ_COMMITTED_SNAPSHOT OFF 
 
ALTER DATABASE [{DBNAME}] SET HONOR_BROKER_PRIORITY OFF 
 
ALTER DATABASE [{DBNAME}] SET RECOVERY SIMPLE 
 
ALTER DATABASE [{DBNAME}] SET  MULTI_USER 
 
ALTER DATABASE [{DBNAME}] SET PAGE_VERIFY CHECKSUM  
 
ALTER DATABASE [{DBNAME}] SET DB_CHAINING OFF 
 
ALTER DATABASE [{DBNAME}] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
 
ALTER DATABASE [{DBNAME}] SET TARGET_RECOVERY_TIME = 60 SECONDS 
 
ALTER DATABASE [{DBNAME}] SET DELAYED_DURABILITY = DISABLED 
 
ALTER DATABASE [{DBNAME}] SET QUERY_STORE = OFF 
 
USE [master] 
 
ALTER DATABASE [{DBNAME}] SET  READ_WRITE 
 
